Previously, the cli parsing support did not support subcommands. Now, you can write a cli with multiple subcommands like this: ``` USAGE:   app COMMAND [OPTIONS] COMMANDS:   help     Print this help message   version  Show version information   test     Run tests See 'app help <command>' for more information on a specific command. ```
The output for "app help <command>" looks like this:

```
USAGE:
  app test [OPTIONS] [project ...]

DESCRIPTION:
  Run tests

OPTIONS:
  --verbose
  --max-count Int (default: 0)
    The maximum number of files to test

  Advanced:
  --magic-number Int (default: 42)

EXAMPLES:
  app test --max-count=100 project-name
```

Error messages when parsing command-line arguments have also improved.

"Did you mean" when invalid argument has similar name to a valid argument
```
error: no such subcommand 'versionn'.
	Did you mean 'app version'?
	Try 'app help' for more information.
error: found argument '--max' which wasn't expected, or isn't valid in this context.
	Did you mean '--max-count'?
```

No "Did you mean" message when names are very different
```
error: no such subcommand 'unknown'.
	Try 'app help' for more information.
error: found argument '--banana' which wasn't expected, or isn't valid in this context.
```

Help messages such as option descriptions are automatically line-wrapped according to the width of the terminal. For example in when listing subcommands with `help`

```
COMMANDS:
  help     Print this help message
  version  Show version information
  test     Run tests in parallel when possible and otherwise will run
           synchronously such as in Scala.js and Scala Native.
```

For example when listing more information about a command with `help COMMAND`
```
DESCRIPTION:
  Run tests in parallel when possible and otherwise will run synchronously such
  as in Scala.js and Scala Native.

OPTIONS:
  --verbose
  --max-count Int (default: 0)
    The maximum number of files to test. If this number exceeds 100 then the
    default because negative, so be sure not to use a very large number.
```